<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $category
 * @property string $feature_name
 * @property string $feature_value
 * @property decimal $monthly
 * @property decimal $quarterly
 * @property decimal $semi_annually
 * @property string $whm_url
 * @property Category $Category
 * 
 * @method string   getName()          Returns the current record's "name" value
 * @method integer  getCategory()      Returns the current record's "category" value
 * @method string   getFeatureName()   Returns the current record's "feature_name" value
 * @method string   getFeatureValue()  Returns the current record's "feature_value" value
 * @method decimal  getMonthly()       Returns the current record's "monthly" value
 * @method decimal  getQuarterly()     Returns the current record's "quarterly" value
 * @method decimal  getSemiAnnually()  Returns the current record's "semi_annually" value
 * @method string   getWhmUrl()        Returns the current record's "whm_url" value
 * @method Category getCategory()      Returns the current record's "Category" value
 * @method Service  setName()          Sets the current record's "name" value
 * @method Service  setCategory()      Sets the current record's "category" value
 * @method Service  setFeatureName()   Sets the current record's "feature_name" value
 * @method Service  setFeatureValue()  Sets the current record's "feature_value" value
 * @method Service  setMonthly()       Sets the current record's "monthly" value
 * @method Service  setQuarterly()     Sets the current record's "quarterly" value
 * @method Service  setSemiAnnually()  Sets the current record's "semi_annually" value
 * @method Service  setWhmUrl()        Sets the current record's "whm_url" value
 * @method Service  setCategory()      Sets the current record's "Category" value
 * 
 * @package    tuxnode
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('category', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('feature_name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('feature_value', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('monthly', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('quarterly', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('semi_annually', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('whm_url', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}