<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/17 16:48:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tuxnode',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
