<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/20 05:29:47
sfConfig::add(array(
  'mod_reseller_hosting_enabled' => true,
  'mod_reseller_hosting_view_class' => 'sfPHP',
));
