<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/17 16:49:56
sfConfig::add(array(
  'mod_sfcryptocaptcha_enabled' => true,
  'mod_sfcryptocaptcha_view_class' => 'sfPHP',
));
