<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/20 05:30:11
sfConfig::add(array(
  'mod_sfcryptocaptcha_enabled' => true,
  'mod_sfcryptocaptcha_view_class' => 'sfPHP',
));
