<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/20 02:09:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tuxnode_main',
  'username' => 'tuxnode_main',
  'password' => ',5Zn#Af{S}[m',
  'name' => 'doctrine',
)),);
