<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/20 05:06:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tuxnode',
  'username' => 'root',
  'password' => 'illualidb',
  'name' => 'doctrine',
)),);
