<?php

/**
 * ServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Service');
    }

    public function getHomePlans($category) {
      return $this->createQuery('a')
          ->leftJoin('a.Category c')
          ->where('c.name = ?', $category)
          ->orderBy('a.annually ASC')
          ->limit(1)
          ->execute();
    }
}