# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Tuxnode - Framework Hosting
    description:  We are providing advanced framework hosting solutions for zend framework, symfony , cake php, code igniter etc
    keywords:     symfony hosting, zend framework , web hosting reseller hosting
    language:     en
    robots:       index, follow

  stylesheets:    [main.css, reset.css, style.css, uttons.css, litegrey.css]

  javascripts:    [jquery-1.4.min.js, jquery.easing.min.js, jquery.tipsy.js, custom.js, cufon-yui.js, Dezen_Pro_Regular.js]

  has_layout:     true
  layout:         layout
