<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('resource', 'resource_feature_service_id');
        $this->createForeignKey('resource', 'resource_feature_feature_id', array(
             'name' => 'resource_feature_feature_id',
             'local' => 'feature',
             'foreign' => 'id',
             'foreignTable' => 'feature',
             ));
        $this->addIndex('resource', 'resource_feature', array(
             'fields' => 
             array(
              0 => 'feature',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('resource', 'resource_feature_service_id', array(
             'name' => 'resource_feature_service_id',
             'local' => 'feature',
             'foreign' => 'id',
             'foreignTable' => 'service',
             ));
        $this->dropForeignKey('resource', 'resource_feature_feature_id');
        $this->removeIndex('resource', 'resource_feature', array(
             'fields' => 
             array(
              0 => 'feature',
             ),
             ));
    }
}