<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/20 05:17:54
sfConfig::add(array(
  'mod_moneyback_guarantee_enabled' => true,
  'mod_moneyback_guarantee_view_class' => 'sfPHP',
));
